# Generated by Django 3.1.7 on 2021-04-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usertype')),
            ],
        ),
    ]
