# Generated by Django 3.1.7 on 2021-04-30 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='class',
            fields=[ 
                ('id', models.AutoField(primary_key=True, null=False, editable=False, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'))
            ],
        ),
        migrations.CreateModel(
            name='date_class',
            fields=[
                ('id', models.AutoField(primary_key=True, null=False, editable=False, unique=True)),
                ('class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class')),
                ('date', models.DateTimeField()),
                ('is_checking', models.BooleanField(default=False)),
            ],
        ),

        migrations.CreateModel(
            name='student_attending',
            fields=[
                ('id', models.AutoField(primary_key=True, null=False, editable=False, unique=True)),
                ('is_attending', models.BooleanField()),
                ('dateClass',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.date_class')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='detail_student_attend_class',
            fields=[
                ('id', models.AutoField(primary_key=True, null=False, editable=False, unique=True)),
                ('class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.class')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        )
    ]
