# Generated by Django 3.2 on 2021-05-10 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_infomation'),
    ]

    operations = [
        migrations.RenameModel(old_name='student_attending',
                               new_name='student_attendances'),
        migrations.RenameModel(old_name='user_type', new_name='user_types'),
        migrations.RenameModel(old_name='date_class', new_name='dates_of_class'),
        migrations.RenameModel(old_name='subject', new_name='subjects'),
        migrations.RenameModel(old_name='user', new_name='users'),
        migrations.RenameModel(old_name='class', new_name='classes'),
        migrations.RenameModel(old_name='detail_student_attend_class', new_name='details_student_attend_class')
    ]
