# Generated by Django 3.2 on 2021-05-10 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_tables'),
    ]

    operations = [
        migrations.RenameField(model_name='student_attendances',
                               old_name='id', new_name='student_attendace_id'),
        migrations.RenameField(model_name='student_attendances',
                               old_name='dateClass', new_name='date_class')
    ]
