# Generated by Django 3.2.6 on 2021-08-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210527_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates_class',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user_types'),
            preserve_default=False,
        ),
    ]
