# Generated by Django 3.2.6 on 2021-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_change_null_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='face_vectors',
            field=models.TextField(null=True),
        ),
    ]
