# Generated by Django 3.2 on 2021-05-10 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_update_field_names_student_attendances'),
    ]

    operations = [
        migrations.RenameField(model_name='user_types', old_name='id', new_name='user_type_id')
    ]
