# Generated by Django 3.2 on 2021-05-10 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_field_names_subjects'),
    ]

    operations = [
        migrations.RenameField(model_name='users', old_name='id', new_name='user_id'),
        migrations.RenameField(model_name='users', old_name='user_name', new_name='full_name')
    ]
