# Generated by Django 3.2 on 2021-05-10 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_update_field_names_users'),
    ]

    operations = [
        migrations.RenameField(model_name='classes', old_name='id', new_name='class_id'),
        migrations.RemoveField(model_name='classes', name='class_name')
    ]
