# Generated by Django 3.2 on 2021-05-10 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_field_names_classes'),
    ]

    operations = [
        migrations.RenameField(model_name='details_student_attend_class', old_name='id', new_name='detail_student_class_id')
    ]
