# Generated by Django 3.1.7 on 2021-04-30 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studentAPI', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DateClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.class')),
                ('Date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.date')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isAttending', models.BooleanField()),
                ('dateClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.dateclass')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetailStudentAttendClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.class')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentAPI.user'),
        ),
    ]
